packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/utils': 0.4.0
  '@trpc/client': ^11.16.0
  '@trpc/server': ^11.16.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  better-auth: 1.6.9
  dotenv: ^17.2.2
  elysia: ^1.4.28
  lucide-react: ^0.546.0
  next-themes: 'catalog:'
  react: ^19.2.3
  react-dom: ^19.2.3
  sonner: 'catalog:'
  tailwindcss: ^4.1.18
  tsx: ^4.21.0
  typescript: ^6
  zod: ^4.1.13
